version: "3"
services:
    pushpin-stream:
        env_file: 
          - creds.env
        build: ./pushpin
        volumes:
            - ./pushpin:/src
            #- ./pushpin/config:/etc/pushpin
        ports:
            - "7999:7999"
            - "5560:5560"
            - "5561:5561"
            - "5562:5562"
            - "5563:5563"
    nasaapi-client:
        env_file: 
            - creds.env
        build: ./nasaapi_client/
        ports:
            - "5000:5000"
        volumes:
            - "./nasaapi_client:/src"