version: "3"
services:
    # pushpin-stream:
    #     env_file: 
    #       - creds.env
    #     build: ./pushpin
    #     volumes:
    #         - ./pushpin:/src
    #     ports:
    #         - "7999:7999"
    nasaapi-client:
        env_file: 
            - creds.env
        build: ./nasaapi_client/
        ports:
            - "5000:5000"
        volumes:
            - "./nasaapi_client:/src"